"""user-hospital

Revision ID: 0910d540937a
Revises: f4c630ad85bd
Create Date: 2025-08-13 07:03:09.016409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0910d540937a'
down_revision: Union[str, None] = 'f4c630ad85bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('admin', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'hospitals', ['admin'])
    op.create_foreign_key(None, 'hospitals', 'users', ['admin'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_column('hospitals', 'admin')
    # ### end Alembic commands ###
